##### APIs

### root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "firstName": "Pariwesh",
    "lastName": "Tamrakar",
    "username": "pariwesh7",
    "email": "a@b.com",
    "password": "12345678"
}

##### Email APIs

### verify user email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "811280",
    "email": "a@a.com"
}


### LOGIN USER
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "username": "pariwesh7",
    "password": "12345678"
}



##### Category Router

### Get Categories
GET http://localhost:8000/api/v1/category/


### Post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name": "Mercurial Superfly",
    "parentCategory": "617b95fcb98c01845dd32562"
}



########### TOKEN ROUTERS

### Get new access token
GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTYzNjI0NjAxNiwiZXhwIjoxNjM4ODM4MDE2fQ.VyAB2JqvowX1KZYIDCIukCMmgFJ1ndds41PXnQ3rsHE